### ISSUE TITLE
Не устанавливается в Termux

### ISSUE THREAD

**Issue by dmitrijkotov634** [crinny/b0mb3r-beta#1]
Не устанавливается в termux

![Screenshot_2019-11-29-12-56-36-826_com termux](https://user-images.githubusercontent.com/53375304/69860628-b4c6fe80-12a7-11ea-801b-d0175f67a2b9.jpg)

 
1) Открыть termux
2) Ввести команду

 - ОС: Android 9.0
 - Версия b0mb3r: 2.0

**Comment by GTmix** [comment]
Так и какое решение?

**Comment by crinny** [comment]
решение: ждать фикс

**Comment by crinny** [comment]
хотя оно мб и так уже работает
