### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Heckfy21** [crinny/b0mb3r-beta#2]
## Описание бага 
Краткое и понятное описание возникшего бага. Ошибка в Termux
ERROR: HTTP error 404 while getting https://github.com/crinny/b0mb3r/archive/master.zip
  ERROR: Could not install requirement https://github.com/crinny/b0mb3r/archive/master.zip because of error 404 Client Error: Not Found for url: https://github.com/crinny/b0mb3r/archive/master.zip
ERROR: Could not install requirement https://github.com/crinny/b0mb3r/archive/master.zip because of HTTP error 404 Client Error: Not Found for url: https://github.com/crinny/b0mb3r/archive/master.zip for URL https://github.com/crinny/b0mb3r/archive/master.zip

## Возпроизведение
Укажите шаги для повторения бага, то что нужно сделать, чтобы возпроизвести его:
1. Запустить Termux
2. Написать команду которая указана на гитхабе для андроид
3. Начинается ядерный апокалипсис .

## Предполагаемое поведение
Краткое и понятное описание того, что вы ожидали увидеть.
Установленный бомбер))

## Дополнительная информация
 - ОС: Android
 - Версия b0mb3r: 2.0

**Comment by crinny** [comment]
Новая команда указана в README - 
```sh
pip install https://github.com/crinny/b0mb3r-beta/archive/master.zip --upgrade
```
