### ISSUE TITLE
Ошибка при запуске (ошибка сегминтации)

### ISSUE THREAD

**Issue by themakci7m87** [crinny/b0mb3r-beta#4]
Установил, запустил, либо ошибка сегментации (segmentation fault)
Либо 
[1]+  Stopped                 b0mb3r

[1]+ Stopped                  b0mb3r
![Screenshot_2019-11-30-09-44-12](https://user-images.githubusercontent.com/50808593/69896946-00d07c80-1356-11ea-8382-708583348ab5.png)

**Comment by crinny** [comment]
Попробуй это - https://github.com/termux/termux-packages/issues/2129#issuecomment-364743651

**Comment by themakci7m87** [comment]
Не помогло такая же ошибка, пробовал на 14 и на 16 (commit'е b0mb3r'a) ошибка также вылетает при окончание установки
![IMG_20191201_101737](https://user-images.githubusercontent.com/50808593/69910895-14e2af80-1424-11ea-908b-6fced2d3f6d2.png)

**Comment by crinny** [comment]
> 
> 
> Не помогло такая же ошибка, пробовал на 14 и на 16 (commit'е b0mb3r'a) ошибка также вылетает при окончание установки
> ![IMG_20191201_101737](https://user-images.githubusercontent.com/50808593/69910895-14e2af80-1424-11ea-908b-6fced2d3f6d2.png)

Попробуй переустановить Termux

**Comment by prostomarkeloff** [comment]
Segmentation Fault - сишная ошибка, падает когда происходит что-то не так в коде интерпретатора питона.

**Comment by crinny** [comment]
> 
> 
> Segmentation Fault - сишная ошибка, падает когда происходит что-то не так в коде интерпретатора питона.

че умный типа да????

**Comment by crinny** [comment]
уу грра я ебу систему в рот

**Comment by themakci7m87** [comment]
Хмм..... страно переустановил
Ошибка та же 
Хотел установить через Parallel Space, но там не работает Termux.
Поэтому пришлось переустановить Termux
Перед установкой b0mb3r'a установил свои коды:
pkg install git -y
pkg install nano -y
pkg install python -y
pkg install python2 -y
pkg install w3m -y
pkg install nmap -y 
pkg install mpv
git clone https://github.com/Hydra7/Planetwork-DDOS
git clone https://github.com/thewhiteh4t/seeker
git clone https://github.com/thelinuxchoice/shellphish

И вот после этих установок я поставил b0mb3r
![Screenshot_2019-12-01-23-10-51](https://user-images.githubusercontent.com/50808593/69919661-750f3b00-1490-11ea-94d6-11ac464f1021.png)

**Comment by crinny** [comment]
Попробуй запустить бомбер в failsafe режиме.

**Comment by themakci7m87** [comment]
Так ладно, я зашел в `failsafe`, но там команду не видит, пошел по пути `/data/data/com.termux/files/usr/bin `там есть файл `b0mb3r`, но как его запустить?

**Comment by themakci7m87** [comment]
Ошибка с новыми обнова не изменилась

**Comment by crinny** [comment]
Каким обновлением?

**Comment by themakci7m87** [comment]
Когда писал коммени был 16 commit твоего кода, проверил 21 commit ошибка та же. Стати если не лень можешь рассказать что ты обновляешь?
![Screenshot_2019-12-06-18-58-48](https://user-images.githubusercontent.com/50808593/70336667-a013d900-185a-11ea-8d3d-c3134259fa6d.png)

**Comment by crinny** [comment]
Это были не обновления, а скорее маленькие визуальные изменения. Об изменениях, пока а бете, писать не буду

**Comment by themakci7m87** [comment]
Еще чучуть решил поэкспериментировать запустить b0mb3r в перерыве от своего кода и в итоге мы получили это результаттест:
1. Решил поскачивать аддоны, компоненты или как там оно называется, щас объясню
В файле b0mb3r/__main__.py вроде такой путь есть строчки import и значение допустим y, ну я решил прописать pip install (и те значения которые я назвал "y") - не помогло, половину не находило
2. VPN не помогает, по крайне мере мой установленный
3. Открыл /data/data/com.termux/files/usr/bin скопировал файл b0mb3r на $HOME запустил там результата нету, chmod x- так перезапускал результат тот же, снова chmod x+ ОПЯТЬ ОШИБКА. ШОШ ТАК НЕ ВЕЗЁТ

**Comment by themakci7m87** [comment]
Стати почему github.com уберает символ __ странно я писал __main__.py а оно убралось, а крч это жирный текст

**Comment by crinny** [comment]
закрываю потому что могу себе позволить
