### ISSUE TITLE
API не работает

### ISSUE THREAD

**Issue by crinny** [crinny/b0mb3r-beta#7]
![image](https://user-images.githubusercontent.com/42045258/69914757-e4693880-1458-11ea-89b0-d1953fff637d.png)

**Comment by catofsof** [comment]
почени буг
`js
console.log('сьел бомбер')
`

**Comment by crinny** [comment]
> 
> 
> почени буг
> `console.log('сьел бомбер')`

бан кста

**Comment by catofsof** [comment]
ок

**Comment by crinny** [comment]
> 
> 
> ок

ебучие твинки маркелова

**Comment by catofsof** [comment]
это кирил сылка балбес

**Comment by crinny** [comment]
> 
> 
> это кирил сылка балбес

а ок люблю (love)

**Comment by catofsof** [comment]
я тоже прив

**Comment by valnesfjord** [comment]
Api работает только при определенной последовательности. Вот:
![1578473152583](https://user-images.githubusercontent.com/56297248/71963383-93452500-320c-11ea-8475-043a015a5aeb.jpg)

**Comment by catofsof** [comment]
кринни, нужна документация намного больше, в мелком куске ничего не понятно. я как обычно отправлял жсон в пост запросе и ничего не работало. чени апи!!!

**Comment by crinny** [comment]
> кринни, нужна документация намного больше, в мелком куске ничего не понятно. я как обычно отправлял жсон в пост запросе и ничего не работало. чени апи!!!

ты кто такой!!!

**Comment by crinny** [comment]
слыш дизлайк свой убрал быстро а то фиксить не буду

**Comment by catofsof** [comment]
> слыш дизлайк свой убрал быстро а то фиксить не буду

убрал прости крини...

**Comment by kesha1225** [comment]
API работает 
![TX9gFhFwu5w](https://user-images.githubusercontent.com/48860626/72248005-2ca67980-3607-11ea-8989-109260adbaea.jpg)
