### ISSUE TITLE
Не работает бомбер

### ISSUE THREAD

**Issue by mrS4mer** [crinny/b0mb3r-beta#8]
## 
1. Запустить
2. Выдаётся ошибка (error code: 400)

## Предполагаемое поведение
Бомбер запускается

## Скриншоты
Если скриншоты могут помочь описанию проблемы, приложите их.

## Дополнительная информация
 - ОС: OneUi 9
 - Браузер: Google Chrome
 - Версия b0mb3r: 2.0

**Comment by crinny** [comment]
Можешь приложить скриншот из браузера и Termux?

**Comment by mrS4mer** [comment]
> Можешь приложить скриншот из браузера и Termux?

![Screenshot_20191202-092520_Chrome](https://user-images.githubusercontent.com/37505900/69935808-07422e00-14e7-11ea-938b-ba8fb907e4bd.jpg)

**Comment by crinny** [comment]
> > Можешь приложить скриншот из браузера и Termux?
> 
> ![Screenshot_20191202-092520_Chrome](https://user-images.githubusercontent.com/37505900/69935808-07422e00-14e7-11ea-938b-ba8fb907e4bd.jpg)

Покажи, какие значения ты вводишь

**Comment by mrS4mer** [comment]
> > > Можешь приложить скриншот из браузера и Termux?
> > 
> > 
> > ![Screenshot_20191202-092520_Chrome](https://user-images.githubusercontent.com/37505900/69935808-07422e00-14e7-11ea-938b-ba8fb907e4bd.jpg)
> 
> Покажи, какие значения ты вводишь

![Screenshot_20191202-093918_Chrome](https://user-images.githubusercontent.com/37505900/69936065-b3841480-14e7-11ea-8e4f-6cdf9d4341d3.jpg)

**Comment by themakci7m87** [comment]
Ну чел это твоя ошибка или может быть всего какой-то сервис работает не стабильно 
![Screenshot_2019-12-02-10-00-00](https://user-images.githubusercontent.com/50808593/69937064-bfbda100-14ea-11ea-9028-1f315747e5cb.png)
![Screenshot_2019-12-02-09-59-48](https://user-images.githubusercontent.com/50808593/69937074-c5b38200-14ea-11ea-97f9-58d341aab5fe.png)

**Comment by crinny** [comment]
Если это моя ошибка, почему у меня работает?

**Comment by triedgriefdev** [comment]
Проверь правильный ли номер, может быть не та длина.

**Comment by kesha1225** [comment]
Все починено закрывайте

**Comment by crinny** [comment]
работает
